-- 021: 用户画像字段
ALTER TABLE users ADD COLUMN city TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN province TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN industries TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN company_type TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN interests TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN bio TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN notify_prefs TEXT DEFAULT '{}';
